api_platform:
  formats:
    json : ['application/json']
    jsonld: ['application/ld+json']
    html: ['text/html']
    multipart: ['multipart/form-data']
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header